/**
 * Withdrawals Data Access Layer
 * Hybrid loading: DB Cache + Delta Sync from Match-Trade API
 * Created: 2025-12-29
 * Mission: MISSION-20251229-0001 - Hybrid Data Loading Architecture
 */

import { createServerClient } from '@/lib/supabase';
import {
  fetchWithdrawalsFromMatchTrade,
  mapPaymentStatus,
  type MatchTradePaymentRecord,
} from '@/lib/api/payments';
import { mergeAndSortWithdrawals } from './merge';
import {
  getLastSyncedAt,
  getSyncTimestamp,
  withTimeout,
  formatDuration,
} from './sync';
import type { Withdrawal, WithdrawalMappedStatus } from '@/types/supabase';
import type { PaymentStats, WithdrawalEvent } from '@/types/payment';

// ============================================================================
// Types
// ============================================================================

export interface HybridWithdrawalsResult {
  withdrawals: WithdrawalEvent[];
  stats: PaymentStats;
  metadata: {
    source: 'hybrid' | 'cache-only' | 'api-only';
    dbCount: number;
    deltaCount: number;
    totalCount: number;
    lastSyncedAt: string;
    fetchedAt: string;
    duration: number;
    apiAvailable: boolean;
    warning?: string;
  };
}

export interface GetWithdrawalsOptions {
  limit?: number;
  status?: 'PENDING' | 'APPROVED' | 'REJECTED' | 'ALL';
  forceRefresh?: boolean;
  apiTimeout?: number;
}

// ============================================================================
// Configuration
// ============================================================================

const DEFAULT_LIMIT = 10000;  // Load all data for scrolling
const DEFAULT_API_TIMEOUT = 5000; // 5 seconds for larger dataset
const DELTA_SYNC_BUFFER_MS = 1000; // 1 second buffer for clock drift
const SUPABASE_PAGE_SIZE = 1000;   // Supabase max rows per query

// ============================================================================
// Supabase Pagination Helper
// ============================================================================

/**
 * Fetch all records from Supabase with pagination
 * Supabase limits to 1000 rows per query, so we fetch in batches
 */
async function fetchAllFromSupabase(
  supabase: ReturnType<typeof createServerClient>,
  options: {
    status: 'PENDING' | 'APPROVED' | 'REJECTED' | 'ALL';
    limit: number;
  }
): Promise<Withdrawal[]> {
  const { status, limit } = options;
  const allRecords: Withdrawal[] = [];
  let offset = 0;

  while (allRecords.length < limit) {
    const pageSize = Math.min(SUPABASE_PAGE_SIZE, limit - allRecords.length);

    let query = supabase
      .from('withdrawals')
      .select('*')
      .order('created_at', { ascending: false })
      .range(offset, offset + pageSize - 1);

    if (status !== 'ALL') {
      query = query.eq('mapped_status', status);
    }

    const { data, error } = await query;

    if (error) {
      console.error('[Withdrawals] Supabase query error:', error);
      throw error;
    }

    if (!data || data.length === 0) {
      break; // No more records
    }

    allRecords.push(...data);
    offset += pageSize;

    // If we got less than page size, we've reached the end
    if (data.length < pageSize) {
      break;
    }
  }

  console.log(`[Withdrawals] Fetched ${allRecords.length} records from Supabase (${Math.ceil(offset / SUPABASE_PAGE_SIZE)} pages)`);
  return allRecords;
}

// ============================================================================
// Data Transformation
// ============================================================================

/**
 * Transform Match-Trade API record to Supabase Withdrawal format
 */
export function transformToWithdrawal(record: MatchTradePaymentRecord): Withdrawal {
  const mappedStatus = mapPaymentStatus(
    record.paymentRequestInfo.financialDetails.status
  ) as WithdrawalMappedStatus;

  return {
    id: '', // Will be generated by Supabase
    uuid: record.uuid,
    account_uuid: record.accountInfo.accountUuid,
    account_email: record.accountInfo.email || null,
    account_name: record.accountInfo.personalDetails?.firstname || null,
    account_surname: record.accountInfo.personalDetails?.lastname || null,
    amount: record.paymentRequestInfo.financialDetails.amount || 0,
    net_amount: record.paymentRequestInfo.financialDetails.netAmount || null,
    currency: record.paymentRequestInfo.financialDetails.currency || 'USD',
    status: record.paymentRequestInfo.financialDetails.status,
    mapped_status: mappedStatus,
    payment_gateway_uuid: record.paymentRequestInfo.paymentGatewayDetails?.uuid || null,
    payment_gateway_name: record.paymentRequestInfo.paymentGatewayDetails?.name || null,
    wallet_address: record.paymentRequestInfo.additionalInfo?.walletAddress || null,
    reference: record.paymentRequestInfo.additionalInfo?.reference || null,
    payment_id: record.paymentRequestInfo.additionalInfo?.paymentId || null,
    partner_id: record.partnerId || null,
    created_at: record.created,
    updated_at: record.created, // Use created as initial updated_at
    synced_at: new Date().toISOString(),
    raw_data: record as unknown as Withdrawal['raw_data'],
  };
}

/**
 * Transform Supabase Withdrawal to UI WithdrawalEvent format
 */
export function transformToWithdrawalEvent(withdrawal: Withdrawal): WithdrawalEvent {
  return {
    uuid: withdrawal.uuid,
    timestamp: withdrawal.created_at,
    accountInfo: {
      uuid: withdrawal.account_uuid,
      email: withdrawal.account_email || '',
      name: withdrawal.account_name || '',
      surname: withdrawal.account_surname || '',
    },
    status: withdrawal.mapped_status,
    amount: withdrawal.amount,
    currency: withdrawal.currency,
    method: withdrawal.payment_gateway_name || undefined,
  };
}

/**
 * Calculate statistics from withdrawals
 */
export function calculateStats(withdrawals: Withdrawal[]): PaymentStats {
  const stats: PaymentStats = {
    totalAmount: 0,
    totalCount: withdrawals.length,
    pendingCount: 0,
    approvedCount: 0,
    rejectedCount: 0,
    pendingAmount: 0,
    approvedAmount: 0,
    rejectedAmount: 0,
  };

  for (const w of withdrawals) {
    stats.totalAmount += w.amount;

    switch (w.mapped_status) {
      case 'PENDING':
        stats.pendingCount++;
        stats.pendingAmount += w.amount;
        break;
      case 'APPROVED':
        stats.approvedCount++;
        stats.approvedAmount += w.amount;
        break;
      case 'REJECTED':
        stats.rejectedCount++;
        stats.rejectedAmount += w.amount;
        break;
    }
  }

  return stats;
}

// ============================================================================
// Main Hybrid Loader
// ============================================================================

/**
 * Hybrid Withdrawals Loader
 *
 * Strategy:
 * 1. Fetch cached data from Supabase (fast, ~50ms)
 * 2. In parallel, fetch delta from Match-Trade API (since last_synced_at)
 * 3. Merge with timestamp-based deduplication
 * 4. Return combined result
 *
 * Fallback:
 * - If API fails/times out, return cached data only with warning
 */
export async function getWithdrawalsHybrid(
  options: GetWithdrawalsOptions = {}
): Promise<HybridWithdrawalsResult> {
  const {
    limit = DEFAULT_LIMIT,
    status = 'ALL',
    apiTimeout = DEFAULT_API_TIMEOUT,
  } = options;

  const startTime = Date.now();
  const supabase = createServerClient();

  // Get last sync timestamp for delta query
  const lastSyncedAt = await getLastSyncedAt('withdrawals');
  const syncTimestamp = getSyncTimestamp(lastSyncedAt, DELTA_SYNC_BUFFER_MS);

  // Parallel fetch: DB (cached with pagination) + API (delta)
  const [dbResult, deltaResult] = await Promise.allSettled([
    // DB: Fetch all records with pagination (Supabase limits to 1000 per query)
    fetchAllFromSupabase(supabase, { status, limit }),

    // Delta: New/updated records from API with timeout
    withTimeout(
      fetchWithdrawalsFromMatchTrade({
        from: syncTimestamp,
        size: 100, // Fetch more to catch all deltas
        sort: 'created,desc',
      }),
      apiTimeout
    ),
  ]);

  // Process DB result
  let dbData: Withdrawal[] = [];
  if (dbResult.status === 'fulfilled') {
    dbData = dbResult.value || [];
  } else {
    console.error('[Withdrawals] DB fetch failed:', dbResult.reason);
    throw new Error('Database unavailable');
  }

  // Process API delta result
  let deltaData: Withdrawal[] = [];
  let apiAvailable = true;
  let warning: string | undefined;

  if (deltaResult.status === 'fulfilled') {
    // Transform API records to Withdrawal format
    deltaData = (deltaResult.value.content || []).map(transformToWithdrawal);
  } else {
    apiAvailable = false;
    warning = `API unavailable: ${deltaResult.reason?.message || 'Unknown error'}. Showing cached data.`;
    console.warn('[Withdrawals] API delta fetch failed:', deltaResult.reason);
  }

  // Merge and sort
  const { data: mergedData, stats: mergeStats } = mergeAndSortWithdrawals(
    dbData,
    deltaData
  );

  // Apply limit after merge (delta might add new records)
  const limitedData = limit > 0 ? mergedData.slice(0, limit) : mergedData;

  // Transform to UI format
  const withdrawalEvents = limitedData.map(transformToWithdrawalEvent);

  // Calculate stats from merged data
  const paymentStats = calculateStats(mergedData);

  const duration = Date.now() - startTime;

  return {
    withdrawals: withdrawalEvents,
    stats: paymentStats,
    metadata: {
      source: !apiAvailable ? 'cache-only' : deltaData.length > 0 ? 'hybrid' : 'cache-only',
      dbCount: mergeStats.dbCount,
      deltaCount: mergeStats.deltaCount,
      totalCount: mergeStats.mergedCount,
      lastSyncedAt: lastSyncedAt.toISOString(),
      fetchedAt: new Date().toISOString(),
      duration,
      apiAvailable,
      warning,
    },
  };
}

// ============================================================================
// Cache-Only Loader (Fallback)
// ============================================================================

/**
 * Get withdrawals from cache only (no API call)
 * Use when you need guaranteed fast response
 */
export async function getWithdrawalsFromCache(
  options: Omit<GetWithdrawalsOptions, 'forceRefresh' | 'apiTimeout'> = {}
): Promise<HybridWithdrawalsResult> {
  const { limit = DEFAULT_LIMIT, status = 'ALL' } = options;
  const startTime = Date.now();
  const supabase = createServerClient();

  // Use pagination helper to fetch all records (Supabase limits to 1000 per query)
  const withdrawals = await fetchAllFromSupabase(supabase, { status, limit });

  const duration = Date.now() - startTime;
  const lastSyncedAt = await getLastSyncedAt('withdrawals');

  return {
    withdrawals: withdrawals.map(transformToWithdrawalEvent),
    stats: calculateStats(withdrawals),
    metadata: {
      source: 'cache-only',
      dbCount: withdrawals.length,
      deltaCount: 0,
      totalCount: withdrawals.length,
      lastSyncedAt: lastSyncedAt.toISOString(),
      fetchedAt: new Date().toISOString(),
      duration,
      apiAvailable: false,
      warning: 'Serving cached data only',
    },
  };
}

// ============================================================================
// API-Only Loader (Initial Sync)
// ============================================================================

/**
 * Get withdrawals directly from API (no cache)
 * Use for initial sync or when cache is empty
 */
export async function getWithdrawalsFromAPI(
  options: { size?: number } = {}
): Promise<MatchTradePaymentRecord[]> {
  const { size = 100 } = options;

  const response = await fetchWithdrawalsFromMatchTrade({
    size,
    sort: 'created,desc',
  });

  return response.content || [];
}
